# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4bb2e7596630fce0ac9794eee32638ac3b9aa4786956b538d043f5c6c46fc79bc1d6d03520803e30f869515a196680dc18b6408c9bcc1794b1eb992fa163d70

test:
  secret_key_base: b2707bbbc6c104a10a512c30ddf683f462c3ab66b45c55f0a8b286876a3b61f9aa9b65a2775c0e25bbb572f547b080b671825de6b10b9cdb565c2e9e53df421c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
